### ISSUE TITLE
Phrasing is a little bit confusing.

### ISSUE THREAD

**Issue by ranyishere** [ledelaney/biol002#5]
The following statement is a little confusing:

> First, all the DNA that makes up your entire genome exists within every single cell in your entire body.
> That means there is A LOT of DNA in your body; I’ve read enough to stretch from here to the sun (93 million miles), and then to Pluto and back. 

In particular, the part that says "I've read enough" could mean that you have read a lot of material in reference to the aforementioned fact. But I think what you are actually saying is that you have seen it in literature somewhere (the aforementioned fact) and are also saying that there is "enough" DNA to stretch from the Earth to the Sun, then to Pluto and then back.

**Comment by ledelaney** [comment]
good catch, very ambiguous!
